### ISSUE TITLE
Oracle data

### ISSUE THREAD

**Issue by cbertelli** [gem/oq-qgis-server#18]
Maybe I'm only lacking basic information on docker. Is there a way to connect to an Oracle DBMS from inside QGIS Server installed in a docker container? Is there a way to connect oq-qgis-server to an Oracle Instant Client docker?

**Comment by daniviga** [comment]
Hi, QGIS server can connect to any datasource defined in a QGIS project, so essentially if you are able to connect to an Oracle DB for QGIS desktop you should able to use the same source as data provider for QGIS server. There are anyway some conditions that may be satisfied:

- The DB must be reachable by the server too and credentials must be valid: i.e. the server hosting machine must be able to connect to the DB endpoint and credentials set in the project must be valid (which is not always the case if authentication is validated also against the IP). When using the Docker the connection will be performed using the host IP
- The server must have the same library support as client: I'm not an expert in Oracle but if I'm not wrong you need https://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html to be able to use an oracle DB with QGIS on Linux. We are not including that library either because we don't need Oracle support and because of the license. Others are embedding it in their QGIS server docker (see https://github.com/Oslandia/docker-qgis). It's also true that it's very easy to build a container based on our own with the addition of the Oracle library
